config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "lists#index"
  resources :lists, except: [:edit, :update] do
    resources :bookmarks, only: [:create, :destroy]
    resources :reviews, only: :create
  end
  resources :bookmarks, only: :destroy
  resources :reviews, only: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true

end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      @review = Review.new
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
    @review = Review.new(list: @list)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @list = List.find(params[:list_id])
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      @bookmark = Bookmark.new
      render "lists/show", status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to list_path(@review.list)
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Add a movie to your <%= @list.name %> list</h3>
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :comment, placeholder: "Enter a comment about the movie" %>
          <%= f.association :movie, prompt: "Select a movie", input_html: {data: {controller: "tom-select"}} %>
          <%= f.submit class: "btn btn-flat" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand d-flex align-items-center" href="/">
    <img src="<%= asset_path('popcorn.png') %>" width="40" height="40" class="d-inline-block align-top me-2" alt="Logo">
  </a>
  <%= link_to "Create a movie list", new_list_path, class: "btn btn-primary rounded-btn" %>
</nav>



<div class="banner" style="
  background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),
  url('https://static.vecteezy.com/system/resources/thumbnails/070/637/784/small/vintage-cinema-interior-with-red-velvet-seating-and-illuminated-screen-ready-for-movie-presentation-photo.jpeg');
">
  <div class="container text-white py-5">
    <h1>Your Watchlist</h1>
    <p>All your favourite movies in one place.</p>
  </div>
</div>

<div class="container py-5">
  <h3 class="mb-4">Your Lists</h3>

  <div class="row g-4">
    <% @lists.each do |list| %>
      <div class="col-12 col-sm-6 col-md-4 col-lg-3">
        <div class="card shadow-sm h-100">
          <div class="card-body">
            <h5 class="card-title"><%= list.name %></h5>
            <%= link_to "View List", list_path(list), class: "btn btn-primary rounded-btn w-100 mt-2" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container py-5">
        <h3>Create a new list</h3>
        <%= simple_form_for @list do |f| %>
          <%= f.input :name%>
          <%= f.submit class: 'btn btn-primary' %>
          
        <% end %>
      </div>

app/views/lists/show.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand d-flex align-items-center" href="/">
    <img src="<%= asset_path('popcorn.png') %>" width="40" height="40" class="d-inline-block align-top me-2" alt="Logo">
  </a>

  <div class="d-flex gap-2">
    <%= link_to "Create a Movie List", new_list_path, class: "btn btn-primary rounded-btn" %>
  </div>
</nav>


<div class="banner"
  style="background-image:
    linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)),
    url('https://dslv9ilpbe7p1.cloudfront.net/xF71XJm6LoG5LV4jPtYRwQ_store_banner_image.jpeg');
  ">
</div>


<div class="container mt-4">

  <!-- List Header -->
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h1 class="m-0"><%= @list.name %></h1>

    <div class="d-flex gap-2">

      <%= link_to "Home", lists_path, class: "btn btn-primary rounded-btn" %>

      <!-- Add Movie (modal trigger) -->
      <button type="button"
              class="btn btn-primary rounded-btn"
              data-bs-toggle="modal"
              data-bs-target="#staticBackdrop">
        Add a Movie
      </button>

      <!-- Delete List -->
      <%= link_to "Delete List",
                  list_path(@list),
                  data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                  class: "btn btn-danger rounded-btn" %>
    </div>
  </div>


  <!-- Add Movie Modal -->
  <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content p-2">
        <div class="modal-header">
          <h5 class="modal-title">Add a Movie to <%= @list.name %></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
        </div>

        <div class="modal-body">
          <%= simple_form_for [@list, @bookmark] do |f| %>
            <%= f.input :comment, placeholder: "Enter a comment about the movie" %>
            <%= f.association :movie,
                              prompt: "Select a movie",
                              input_html: { data: { controller: "tom-select" } } %>

            <%= f.submit "Add Movie", class: "btn btn-primary mt-2" %>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>




<div class="container py-5">
  <h3 class="mb-4">Movies in this List</h3>

  <div class="row g-4">
    <% @list.bookmarks.each do |bm| %>
      <div class="col-12 col-sm-6 col-md-4 col-lg-3">
        <div class="card shadow-sm h-100">

          <!-- Movie Poster -->
          <% if bm.movie.poster_url.present? %>
            <img src="<%= bm.movie.poster_url %>" class="card-img-top" alt="<%= bm.movie.title %>">
          <% else %>
            <img src="https://via.placeholder.com/400x250?text=No+Poster" class="card-img-top">
          <% end %>

          <div class="card-body d-flex flex-column">
            <h5 class="card-title"><%= bm.movie.title %></h5>
            <p class="text-muted small mb-1">⭐ <%= bm.movie.rating %>/10</p>
            <p class="text-muted small"><%= truncate(bm.movie.overview, length: 80) %></p>

            <% if bm.comment.present? %>
              <p class="fw-bold small mt-2">"<%= bm.comment %>"</p>
            <% end %>

        <%= link_to list_bookmark_path(@list, bm),
            data: { turbo_method: :delete, turbo_confirm: "Remove this movie?" },
            class: "btn btn rounded-btn" do %>
  <i class="fa-solid fa-trash"></i>
<% end %>


          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>